Fix UtxoInterface and test via fetchPrevoutAndTryToUnblindUtxo method
vulpemventures/ldk pull request #43
Opened 2021-03-02 13:55 UTC by Janaka-Steph

2021-03-02 13:59 UTC, tiero commented on src/types.ts
> +  assetcommitment?: string;
I'm not sure this type is the same type you are thinking of. AFAIK this is only used internally, it should not be used to  Esplora JSON response

2021-03-02 14:05 UTC, tiero commented
This opens up a good point: is the current design of `UtxoInterface` covering to much?

ie. it has fields which are used internally (ie. unblindData, prevout) menwhile is also used as return type of `fetchPrevoutAndTryToUnblindUtxo`

2021-03-02 14:17 UTC, tiero commented on src/types.ts
> +  assetcommitment?: string;
nvm, this is actually ok.

2021-03-02 14:46 UTC, tiero requested changes
Discard all previous comments:

1. ACK for EsploraTxInterface  defined in src/esplora/types. Please add it as return type for the method [fetchUtxos](https://github.com/vulpemventures/ldk/blob/6e70276fb169f45f16cc976281c02fe62c2d893f/src/explorer/esplora.ts#L47)
2. nACK for adding status and commitment into UtxoInterface
3. ACK for adding the test  should have fetchPrevoutAndTryToUnblindUtxo return correct utxo interface  in test/esplora.test.ts , which should be renamed to `should return an UtxoInterface with extra esplora enriched fields if the UtxoInterface interface as input contains extra esplora enriched fields`

2021-03-02 21:17 UTC, tiero approved these changes

2021-03-03 11:21 UTC, louisinger approved these changes

2021-03-03 11:30 UTC, merged